#!/usr/bin/env python3
"""
Google Ads Change Approval Workflow

Review and approve/reject pending optimization changes generated by
the autonomous optimizer.

Usage:
    python3 approve_changes.py                    # Interactive mode
    python3 approve_changes.py --list             # List pending changes
    python3 approve_changes.py --approve ID       # Approve specific change
    python3 approve_changes.py --reject ID        # Reject specific change
    python3 approve_changes.py --approve-all      # Approve all pending
    python3 approve_changes.py --reject-all       # Reject all pending
    python3 approve_changes.py --clear            # Clear all pending changes
"""

import os
import sys
import json
import argparse
from datetime import datetime
from pathlib import Path

from google_ads_client import get_client
from google.ads.googleads.errors import GoogleAdsException

# Paths
SCRIPT_DIR = Path(__file__).parent
DATA_DIR = SCRIPT_DIR.parent / "data"
PENDING_FILE = DATA_DIR / "pending_changes.json"
HISTORY_FILE = DATA_DIR / "change_history.json"


def load_pending_changes() -> list:
    """Load pending changes from file."""
    if not PENDING_FILE.exists():
        return []
    with open(PENDING_FILE) as f:
        return json.load(f)


def save_pending_changes(changes: list):
    """Save pending changes to file."""
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    with open(PENDING_FILE, "w") as f:
        json.dump(changes, f, indent=2)


def save_to_history(change: dict, action: str):
    """Save processed change to history."""
    DATA_DIR.mkdir(parents=True, exist_ok=True)

    history = []
    if HISTORY_FILE.exists():
        with open(HISTORY_FILE) as f:
            history = json.load(f)

    history.append({
        **change,
        "action": action,
        "processed_at": datetime.now().isoformat()
    })

    with open(HISTORY_FILE, "w") as f:
        json.dump(history, f, indent=2)


def list_pending_changes(changes: list):
    """Display pending changes."""
    if not changes:
        print("\n  No pending changes.")
        return

    print(f"\n  {len(changes)} pending change(s):\n")
    print("-" * 80)

    for i, change in enumerate(changes):
        change_type = change.get("type", "unknown")
        account_id = change.get("account_id", "")
        timestamp = change.get("timestamp", "")[:19]

        print(f"  [{i}] {change_type.upper()}")
        print(f"      Account: {account_id}")

        if change_type == "pause_keyword":
            print(f"      Keyword: {change.get('keyword', 'N/A')}")
            print(f"      Ad Group: {change.get('ad_group', 'N/A')}")
            metrics = change.get("metrics", {})
            print(f"      Cost: £{metrics.get('cost', 0):.2f}, Clicks: {metrics.get('clicks', 0)}, Conv: {metrics.get('conversions', 0)}")

        elif change_type == "reduce_bid":
            print(f"      Keyword: {change.get('keyword', 'N/A')}")
            print(f"      Current CPC: £{change.get('current_cpc', 0):.2f}")
            print(f"      Suggested: -{change.get('suggested_reduction_pct', 0)}%")

        elif change_type == "increase_bid":
            print(f"      Keyword: {change.get('keyword', 'N/A')}")
            print(f"      Current CPC: £{change.get('current_cpc', 0):.2f}")
            print(f"      Suggested: +{change.get('suggested_increase_pct', 0)}%")

        elif change_type == "add_negative":
            print(f"      Search Term: {change.get('search_term', 'N/A')}")
            print(f"      Campaign: {change.get('campaign', 'N/A')}")
            metrics = change.get("metrics", {})
            print(f"      Cost: £{metrics.get('cost', 0):.2f}, Clicks: {metrics.get('clicks', 0)}")

        print(f"      Reason: {change.get('reason', 'N/A')}")
        print(f"      Created: {timestamp}")
        print("-" * 80)


def apply_change(change: dict) -> bool:
    """Apply a single change. Returns True if successful."""
    change_type = change.get("type")
    account_id = change.get("account_id")

    client = get_client()

    try:
        if change_type == "pause_keyword":
            return apply_pause_keyword(client, account_id, change)
        elif change_type == "reduce_bid":
            return apply_bid_change(client, account_id, change, decrease=True)
        elif change_type == "increase_bid":
            return apply_bid_change(client, account_id, change, decrease=False)
        elif change_type == "add_negative":
            return apply_negative_keyword(client, account_id, change)
        else:
            print(f"  Unknown change type: {change_type}")
            return False
    except GoogleAdsException as ex:
        print(f"  Error applying change: {ex}")
        return False


def apply_pause_keyword(client, account_id: str, change: dict) -> bool:
    """Pause a keyword."""
    keyword = change.get("keyword")
    ad_group = change.get("ad_group")

    print(f"  Pausing keyword '{keyword}' in ad group '{ad_group}'...")

    # Find the keyword criterion
    ga_service = client.get_service("GoogleAdsService")

    query = f"""
        SELECT
            ad_group_criterion.resource_name,
            ad_group_criterion.keyword.text
        FROM keyword_view
        WHERE ad_group_criterion.keyword.text = '{keyword}'
            AND ad_group.name = '{ad_group}'
            AND ad_group_criterion.status = 'ENABLED'
        LIMIT 1
    """

    try:
        response = ga_service.search(customer_id=account_id, query=query)
        for row in response:
            resource_name = row.ad_group_criterion.resource_name

            # Pause the keyword
            from google.protobuf import field_mask_pb2
            criterion_service = client.get_service("AdGroupCriterionService")

            operation = client.get_type("AdGroupCriterionOperation")
            criterion = operation.update
            criterion.resource_name = resource_name
            criterion.status = client.enums.AdGroupCriterionStatusEnum.PAUSED

            operation.update_mask.CopyFrom(field_mask_pb2.FieldMask(paths=["status"]))

            criterion_service.mutate_ad_group_criteria(
                customer_id=account_id,
                operations=[operation]
            )

            print(f"  Successfully paused: {keyword}")
            return True

        print(f"  Keyword not found: {keyword}")
        return False

    except GoogleAdsException as ex:
        print(f"  Error: {ex}")
        return False


def apply_bid_change(client, account_id: str, change: dict, decrease: bool) -> bool:
    """Adjust keyword bid."""
    keyword = change.get("keyword")
    ad_group = change.get("ad_group")

    if decrease:
        pct = change.get("suggested_reduction_pct", 20)
        direction = "Reducing"
    else:
        pct = change.get("suggested_increase_pct", 20)
        direction = "Increasing"

    print(f"  {direction} bid for '{keyword}' by {pct}%...")

    # For now, log only - bid changes are complex and need careful implementation
    print(f"  [NOTE] Bid changes require manual implementation in Google Ads")
    return True


def apply_negative_keyword(client, account_id: str, change: dict) -> bool:
    """Add a negative keyword."""
    search_term = change.get("search_term")
    campaign = change.get("campaign")

    print(f"  Adding negative keyword '{search_term}' to campaign '{campaign}'...")

    # For now, log only - negative keyword implementation needs campaign ID
    print(f"  [NOTE] Add '{search_term}' as negative keyword manually or via API")
    return True


def interactive_mode(changes: list):
    """Interactive review mode."""
    if not changes:
        print("\n  No pending changes to review.")
        return

    print("\n  INTERACTIVE REVIEW MODE")
    print("  Commands: (a)pprove, (r)eject, (s)kip, (q)uit\n")

    remaining = changes.copy()

    for i, change in enumerate(changes):
        print("-" * 60)
        print(f"\n  Change {i+1} of {len(changes)}:")

        change_type = change.get("type", "unknown").upper()
        keyword = change.get("keyword") or change.get("search_term", "N/A")

        print(f"    Type: {change_type}")
        print(f"    Keyword/Term: {keyword}")
        print(f"    Reason: {change.get('reason', 'N/A')}")
        print()

        while True:
            action = input("  Action [a/r/s/q]: ").strip().lower()

            if action == "a":
                print("  Approving and applying...")
                success = apply_change(change)
                save_to_history(change, "approved" if success else "failed")
                remaining.remove(change)
                break

            elif action == "r":
                print("  Rejected.")
                save_to_history(change, "rejected")
                remaining.remove(change)
                break

            elif action == "s":
                print("  Skipped.")
                break

            elif action == "q":
                print("\n  Saving remaining changes and exiting...")
                save_pending_changes(remaining)
                return

            else:
                print("  Invalid input. Use: a (approve), r (reject), s (skip), q (quit)")

    save_pending_changes(remaining)
    print(f"\n  Review complete. {len(remaining)} changes remaining.")


def main():
    parser = argparse.ArgumentParser(description="Approve/reject pending Google Ads changes")
    parser.add_argument("--list", action="store_true", help="List pending changes")
    parser.add_argument("--approve", type=int, metavar="ID", help="Approve change by index")
    parser.add_argument("--reject", type=int, metavar="ID", help="Reject change by index")
    parser.add_argument("--approve-all", action="store_true", help="Approve all pending")
    parser.add_argument("--reject-all", action="store_true", help="Reject all pending")
    parser.add_argument("--clear", action="store_true", help="Clear all pending changes")
    args = parser.parse_args()

    print("\n" + "="*60)
    print("GOOGLE ADS CHANGE APPROVAL")
    print("="*60)

    changes = load_pending_changes()

    if args.list:
        list_pending_changes(changes)

    elif args.clear:
        save_pending_changes([])
        print("\n  All pending changes cleared.")

    elif args.approve is not None:
        if 0 <= args.approve < len(changes):
            change = changes[args.approve]
            print(f"\n  Approving change {args.approve}...")
            success = apply_change(change)
            save_to_history(change, "approved" if success else "failed")
            changes.pop(args.approve)
            save_pending_changes(changes)
        else:
            print(f"\n  Invalid index: {args.approve}")

    elif args.reject is not None:
        if 0 <= args.reject < len(changes):
            change = changes[args.reject]
            print(f"\n  Rejecting change {args.reject}...")
            save_to_history(change, "rejected")
            changes.pop(args.reject)
            save_pending_changes(changes)
        else:
            print(f"\n  Invalid index: {args.reject}")

    elif args.approve_all:
        print(f"\n  Approving all {len(changes)} changes...")
        for change in changes:
            success = apply_change(change)
            save_to_history(change, "approved" if success else "failed")
        save_pending_changes([])
        print("  All changes processed.")

    elif args.reject_all:
        print(f"\n  Rejecting all {len(changes)} changes...")
        for change in changes:
            save_to_history(change, "rejected")
        save_pending_changes([])
        print("  All changes rejected.")

    else:
        # Default: interactive mode
        list_pending_changes(changes)
        if changes:
            print("\n  Enter interactive mode? (y/n): ", end="")
            if input().strip().lower() == "y":
                interactive_mode(changes)

    print()


if __name__ == "__main__":
    main()
